---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      production-npm-dependencies:
        dependency-type: "production"
      development-npm-dependencies:
        dependency-type: "development"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      production-npm-dependencies:
        dependency-type: "production"
      development-npm-dependencies:
        dependency-type: "development"
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      production-npm-dependencies:
        dependency-type: "production"
      development-npm-dependencies:
        dependency-type: "development"
